# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Mistral Client
site_url: https://thomas-marquis.github.io/mistral-client
repo_url: https://github.com/thomas-marquis/mistral-client
repo_name: thomas-marquis/mistral-client
site_author: Thomas Marquis
theme:
  name: material
  language: en
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - toc.follow
    - search
    - search.suggest
    - navigation.footer
    - navigation.top
  favicon: assets/images/logo-tr.png
  logo: assets/images/logo-tr.png
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: amber
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: amber
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Getting started: index.md
  - Basic usage:
      - Initialize the client: basic-usage/init-client.md
      - Perform a basic chat completion: basic-usage/chat-completion.md
      - Constraint the output format: basic-usage/structured.md
      - Call tools: basic-usage/tool-calling.md
      - List and Search models: basic-usage/models.md
      - Embed a text: basic-usage/embed.md
  - Advanced usage:
      - Complex input data: advanced-usage/complex-input.md
      - "Testing: mock the client": advanced-usage/mock.md
      - Rate limiting: advanced-usage/rate-limiting.md
      - Chat completion streaming: advanced-usage/completion-streaming.md
  - Concepts:
      - Content types: concepts/content-types.md
  - References:
      - Client: references/client.md
      - Chat completion: references/chat-completion.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/thomas-marquis
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/thomas-marquis-contact
plugins:
  - privacy:
      links_attr_map:
        target: _blank