[project]
name = "mistral-client"
version = "0.1.0"
description = "An HTTP client for Mistral AI written in Go"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.1",
]
